name: Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose down
    - run: docker-compose build
    - run: docker-compose up -d
